### ISSUE TITLE
example of usage [file] input

### ISSUE THREAD

**Issue by paxapy** [filestack/filestack-angular#5]
I'm trying to provide a file as input into `ng-picker-overlay` like this:
```
<ng-picker-overlay
  [apikey]="apiKey"
  [clientOptions]="clientOptions"
  [file]="inputFile"
  (uploadSuccess)="onUploadSuccess($event)"
  (uploadError)="onUploadError($event)"
>
```
and i expecting that filestack modal will open with provided file selected.
but in fact, it opens empty.
can you please provide some example of this file input usage, or maybe you can suggest a way to provide file into picker to upload?

**Comment by pcholuj** [comment]
Hi sory for late answer, but you cannot open picker with provided file
